#include <stdlib.h>
#include <time.h>
#include <stdio.h>

/**
 *main: this function will determine the last digit of randome variable 
 *@: n is a random variable generated by the program
 *Return: 
 *		5 if it's equal to 5
 *		less than 6 and not equal to 0 if it's like this
 *		or else 0
 **/
int main(void)
{
	int n;

	srand(time(0));
	n = rand() - RAND_MAX / 2;
	
	if ((n % 10) > 5)
	{
		printf("Last digit of %d is %d and is greater than 5\n", n, n % 10);
	}
		else if ((n % 10) < 6 && (n % 10) != 0)
	{
		printf("Last digit of %d is %d and is less than 6 and not 0\n", n, n % 10);
	}
	else
	{
		printf("Last digit of %d is %d and is 0\n", n, n % 10);
	}

	return (0);
}
